### ISSUE TITLE
How can I crosscompile GhostBSD to Raspberry Pi?

### ISSUE THREAD

**Issue by steveunixson** [ghostbsd/ghostbsd-build#10]
It is rather a question more than feature request. How can I crosscompile GhostBSD to Raspberry Pi? I know that FreeBSD has official image for RPi.

**Comment by asxbsd** [comment]
Actually the build scripts are ready for crosscompile i386 from an amd64 arch, and the target is set in ghostbsd-build/conf/ghostbsd.defaults.conf.

After that I guess several of the used scripts need to be adjusted as required ... you can try.

You can reach us on IRC freenode #ghostbsd #ghostbsd-dev

**Comment by vimanuelt** [comment]
This issue is not a planned feature.
