### ISSUE TITLE
KDE

### ISSUE THREAD

**Issue by ericbsd** [GhostBSD/ghostbsd-build#11]
KDE does not boot in the desktop I can not test the installer properly.

**Comment by angelescuo** [comment]
What;s happened ?
Where it hangs ?

**Comment by ericbsd** [comment]
It now  boot to the desktop from my last build , but I can do noting with it freeze in virtual box.

**Comment by ericbsd** [comment]
Wow I did put 3 GB of ram and 2 CORE of my CPU and it barely work fine.

**Comment by ericbsd** [comment]
Will not be supported
