### ISSUE TITLE
build.sh can't find ghostbsd-common-settings

### ISSUE THREAD

**Issue by tomblackwhite** [ghostbsd/ghostbsd-build#115]
when I use "build.sh -d kde" to build kde iso.
But the information is
pkg: No packages available to install matching 'ghostbsd-common-settings' have been found in the repositories.
I use pkg info ghostbsd-common-settings .I can see it. But I use pkg search ghostbsd-common-settings. I can't find it. 
So how to solve it.

**Comment by ericbsd** [comment]
It will be fixed soon we had an x11/Makefile problem in ports. We are building the missing packages.

**Comment by vimanuelt** [comment]
Actually I make the mistake. Eric corrected the mistake. I apologize for the inconvenience.

**Comment by ericbsd** [comment]
Fixed
