### ISSUE TITLE
remove virtual box addition as default

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/ghostbsd-build#118]

**Comment by ericbsd** [comment]
https://github.com/ghostbsd/ghostbsd-build/commit/7a3cd482e90ad76bdfb8cecdcc735a371ea2c8aa

**Comment by grahamperrin** [comment]
Maybe related: [GhostBSD ISO live boot user experience as a VirtualBox guest - Forums](https://forums.ghostbsd.org/viewtopic.php?f=76&t=1873)

**Comment by ericbsd** [comment]
No, I removed it remove some space on the ISO.
