### ISSUE TITLE
Ventroy not working to boot ISO produced by build system

### ISSUE THREAD

**Issue by pkgdemon** [ghostbsd/ghostbsd-build#134]
Reported by neb in telegram forums this sounded similar to a ticket filed against FuryBSD: 

https://github.com/furybsd/furybsd-livecd/issues/169

This combination is known to produce boot issues:
GhostBSD 20.12.25
Ventroy 1.0.27 (latest is .*.35 as of date of making this ticket)

Vas reported that Ventroy worked for him using:
GhostBSD 21.02.01 ISO, and using Ventroy 1.0.33.

Opening a ticket so I can investigate later.

**Comment by pkgdemon** [comment]
![photo_2021-02-21_15-54-16](https://user-images.githubusercontent.com/4109732/108638407-15b69580-745d-11eb-970e-448cd52cfc1a.jpg)
According to Vas "Looking at the history of ventoy, v 1.0. 30, added support for TrueNAS-12.0 Release. So surely, FreeBSD and GBSD by extension should also be supported?"

**Comment by ericbsd** [comment]
Was also reported here https://github.com/ghostbsd/ghostbsd-src/issues/50
and got fix here https://github.com/ventoy/Ventoy/releases/tag/v1.0.41
