### ISSUE TITLE
Bootable flash drive does not work on a computer with multiple operating systems

### ISSUE THREAD

**Issue by Ubuntu-2020** [ghostbsd/ghostbsd-build#147]
**GhostBSD** bootable flash drive **does not work** on a computer with multiple operating systems (GRUB 2.04):
`Enter full pathname of shell or RETURN for /rescue/sh:`
After the above message, the download of the flash drive does not continue.
And at the same time, the same bootable flash drive **works** on a computer with one operating system!
I'm not good with computers, just thought I'd report a bug.

**Comment by ericbsd** [comment]
If you see the Rescue shell that means your system has less than the required amount of ram to run the livecd.

I made the decision to not support less than 4 gigs of ram to have a ZFS on ram live system.
