### ISSUE TITLE
RAM and GhostBSD

### ISSUE THREAD

**Issue by Ubuntu-2020** [ghostbsd/ghostbsd-build#148]
Why does **GhostBSD** consume so much **RAM**?

Please do something so that less than **1 GB of RAM** is consumed and not **3 GB of RAM** as it is now!

Please reduce the consumption of **RAM**!

**Comment by ericbsd** [comment]
I can't lower the ram usage of the live ISO or I will lose the ZFS pool on ram which made the live file system R/W.

There is a disclaimer on the download page and in all release Notes.

```
Minimum System Requirements

    64-bit processor
    4 GB of RAM
    15 GB of free hard drive space
    Network card

Note: GhostBSD can't successfully install in a system with less than 4G of ram because once GhostBSD is booted, it is running from the ram and not from the USB flash drive or DVD.
```

**Comment by Ubuntu-2020** [comment]
@ericbsd Thanks.
But the installed system **GhostBSD** on the hard disk consumes **500-700 MB of RAM**.
I think it would be correct to indicate on the official website that **4 GB is needed to run a flash drive**, and an already installed system will consume about **500-800 MB of RAM**.
