### ISSUE TITLE
xorg not installed after fresh install of GhostBSD KDE 2020.04.03

### ISSUE THREAD

**Issue by fabrice14** [ghostbsd/ghostbsd-build#44]
after install of ghostbsd kde in VM, I checked to start the session kde with a normal user. First, I could not start the session, except as root, with the startx command.
Then, I checked xorg, which is not installed by default. I saw that only wayland was installed (?)

I finally installed xorg, and added (in .xinitrc) the command "exec ck-launcher-session startplasma-x11", which was fine.

I am not sure that it is a bug. How do you plan to start kde with wayland session? 
I tried the command start-plasma-wayland, but not worked.

**Comment by ericbsd** [comment]
did you try the latest build 2020.04.06?
https://download.ghostbsd.org/development/amd64/latest/
A lot of issues fixed on the latest build.

**Comment by ericbsd** [comment]
We don't support way land yet.

**Comment by ericbsd** [comment]
Also, the KDE image is work in progress.

**Comment by fabrice14** [comment]
Ok, I am going to try it. 
Yes, I know that KDE is still in progress. Thank you !

**Comment by fabrice14** [comment]
Sorry for late. It is ok with the latest build 2020.04.06. I close it.
I would like to say congratulations for GhostBSD distrib. It is a good idea to do a based unix system instead of linux. Ghost BSD mate is really stable, and nice for an every day desktop.
