### ISSUE TITLE
Cannot install to USB-HD (20.03)

### ISSUE THREAD

**Issue by thomas-butz** [ghostbsd/ghostbsd-build#46]
I've downloaded the ISO to a USB-stick and can run this - though I can't save a thing
(/usr is write-protected).

How can I install the above stick so I can write to it?

Thanks for your help,

Tom Butz.
]

**Comment by fabrice14** [comment]
Hello,
I am not sure to understand, but for writing on usb stick, as described in the link: https://ghostbsd.org/20.03_release_announcement, you may try to use the command dd ?

On BSD
dd if=GhostBSD-20.03.iso of=/dev/da0 bs=4m

On Linux
dd if=GhostBSD-20.03.iso of=/dev/sdc bs=4M

On Mac
dd if=GhostBSD-20.03.iso of=/dev/disk2 bs=10240

**Comment by fabrice14** [comment]
Hello, 

I am not sure to understand, but for writing on a usb stick, I am using the following command:
did you try this? (it described in the release announcement)

On BSD
dd if=GhostBSD-20.03.iso of=/dev/da0 bs=4m

On Linux
dd if=GhostBSD-20.03.iso of=/dev/sdc bs=4M

On Mac
dd if=GhostBSD-20.03.iso of=/dev/disk2 bs=10240

**Comment by ericbsd** [comment]
GhostBSD is not a full RW live system and that supported might never come sine the only was at the moment is UnionFS and it is buggy right now.

**Comment by ericbsd** [comment]
Oh, and the tickets are not there to ask questions, but to reports, problems or request features. for Support go on the GhostBSD Forum or Telegram Group.

**Comment by thomas-butz** [comment]
Hi there,

thanks for that quick reply.

I did copy the OS to a USB-stick (8G) using dd (Linux) and booted from
this USB-stick.
No problem so far.

When I selected Install from the loaded OS' Desktop I couldn't install
on a USB-HD..
It always aborted with error messages. The USB-HD is a 500G one.

Browsing the Internet off the stick works well, WiFi no problem at all.
I just can';t write to the same stick (/usr is write-protected).

What was I doing wrong?

Tom Butz
=

**Comment by thomas-butz** [comment]
Hi Eric,

thanks for pointing out that the live system is a bit buggy.
I mount an ext2-formatted USB-stick on it and, I can save things there.
I can also sftp things to/from another server-account, so that's not a
problem for me.
The Linux-module apparently is loaded automatically.

Keep up the good work - congrats for your desktop, BTW.

Tom.
=

**Comment by thomas-butz** [comment]
Hi Eric,

I'll need to test the installation of the installation-stick to a
non-USB harddrive
(haven't got one handy, but will get there a bit later). Installing
from USB-stick to
USB-HD always crashed - regardless of selected options. When I was using FreeBSD
a few years ago I had a similar thing happen to me: install from USB-stick to
USB-HD and you get the same fstab on the USB-HD. Easy to fix manually.

Tom.
=

**Comment by ericbsd** [comment]
Like I said the live USB is not fully RW, and for the USB HD I would need the logs to see what is the problem. I need gbi output of `sudo gbi`  in the terminal, I also need /tmp/.gbi/pcinstall.cfg without your password and /tmp/.pc-sysinstall.log.

**Comment by thomas-butz** [comment]
Hi Eric,

I managed to install it on my laptop's internal HD - from the USB
installation stick. It works well, is fast and uses very high screen
resolution, so I didn't change anything there - except for the
Desktop background (right mouseclick).

Installation options: UFS_?? whole disk FreeBSD boot-loader.

What is funny: I tried to install 'joe', an editor I am familiar with,
and 'gopher' with:
pkg install joe and pkg install gopher. That trigerred several hours
of identical messages but didn't do a thing. What was I doing wrong? I
had been using joe under FreeBSD a few years ago.

Thanks for your help,

Tom.

**Comment by thomas-butz** [comment]
Hi Eric,

I needed my laptop back with Mint193 on it, but will keep playing
on GhostBSD off a memory stick.

Your system is blazingly fast - I was able to watch a movie using
Firefox on a WiFi
connection (no fibre, cable ADSL). The laptop has 6 GB of RAM and I
left everything on
single user.


Tom Butz.

**Comment by vimanuelt** [comment]
Closing ticket. Originator did not provide information as requested.
