### ISSUE TITLE
Add boot option to set hw.syscons.disable=1 for AMD/Radeon GPUs.

### ISSUE THREAD

**Issue by vimanuelt** [ghostbsd/ghostbsd-build#48]
For the AMD/RADEON GPUs, add an option in the boot to set hw.syscons.disable=1

**Comment by ericbsd** [comment]
only one thing left to have full support, we need to determine at the installation how to set hw.syscons.disable=1 for radeon and amdgpu.

**Comment by ericbsd** [comment]
done
