### ISSUE TITLE
possible typo in drawer.lua

### ISSUE THREAD

**Issue by grrr2** [ghostbsd/ghostbsd-build#50]
Hi,

I _think_ (absolutely not sure) there is typo in drawer.lua, and try to include logo_ files and not logo-.

```
local function getLogodef(logo)
	if logo == nil then
		return nil
	end
	-- Look it up
	local logodef = logodefs[logo]

	-- Try to pull it in
	if logodef == nil then
		try_include('logo-' .. logo) <--- this is rather (?) 'logo_'
		logodef = logodefs[logo]
	end

	return logodef
end
```
Booting via pxeboot at least complaining cannot index a nil value at line 277 which maybe tracked down to this typo - I _guess_. Sorry if this meant to be like this and mine is a false bug report.

**Comment by ericbsd** [comment]
I have no idea it is a bug or FreeBSD intended it like that.

**Comment by grrr2** [comment]
in the lua directory `logo_*.lua` files exist thus _looks_ like - to me at least without much experience with lua scritping - that should construct the include filename accordingly, and not using the `logo-` format. just an idea (which pretty much explains the error message). if this is coming from upstream might report there too. thanks.

**Comment by vimanuelt** [comment]
Upstream issue. Won't fix.
