### ISSUE TITLE
installation of ghost bsd kde 2020-04-30 failed in vbox

### ISSUE THREAD

**Issue by fabrice14** [ghostbsd/ghostbsd-build#52]
Hello,

The installation of the build ghostbsd KDE 04-30 is failed. I have a zpool error, see picture in attach.
![Capture du 2020-05-01 18-54-07](https://user-images.githubusercontent.com/40697283/80861627-fc472180-8c6f-11ea-9031-58560952cb53.png)

**Comment by vimanuelt** [comment]
Please provide some information about your current VM specifications when error occurred:
(1) Host OS (distro & version):
(2) Version of VirtualBox:
(3) Amount of RAM: 
(4) # of vCPU: 
(5) Size of virtual HDD:

For test:
Please assign 8 GiB of RAM (12 GiB if available).
Please assign only 1 vCPU.
Please assign at least 30 GiB HDD storage.

**Comment by vimanuelt** [comment]
N.B. If the above test fails, or if you cannot assign more resources for testing, please consider installing UFS instead of ZFS.

**Comment by fabrice14** [comment]
Host OS (distro & version): GhostBSD (installed in March 20.02 and update done yesterday)
Version of VirtualBox: 5.2.34 r133883
Amount of RAM assigned to VM: 8192
# of vCPU: 2
Size of virtual HDD: 16GB allocated dynamically on SSD

it works with UFS.

**Comment by fabrice14** [comment]
And I am able to start plasma now. Thank you
