### ISSUE TITLE
Move msd-background-helper to ghostbsd mate setting

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/ghostbsd-build#58]

**Comment by angelescuo** [comment]
Agree .
msd-backgrround helper should be in ghostbsd-mate-settings.
May I do that ?

**Comment by angelescuo** [comment]
msd-background-helper push background for user that started a session.
Why use it since we have already set background for all possible mate users ?
Also background can be pushed also to greeter dm settings.

**Comment by ericbsd** [comment]
msd-background-helper change the lightdm background for each user when the user change is MATE desktop background. So when a user switches the user in the lightdm UI the background change.

**Comment by angelescuo** [comment]
Then is ok and it should be in mate settings .

**Comment by angelescuo** [comment]
Is already moved to mate settings but msd-background helper has issues:

dbus-send --system --print-reply \
	--dest=org.freedesktop.Accounts \
	--type=method_call \
	/org/freedesktop/Accounts/User`id -u` \
	org.freedesktop.Accounts.User.SetBackgroundFile string:"$USERBACKGROUND"

Lines above are useless and should go away  because freedesktop doest'n have method SetBackgroundFile.
It seems that SetBackgroundFile is ubuntu specific.

**Comment by angelescuo** [comment]
Issue should be closed.

**Comment by ericbsd** [comment]
Not completed

> Issue should be closed.

**Comment by ericbsd** [comment]
> Is already moved to mate settings but msd-background helper has issues:
> 
> dbus-send --system --print-reply
> --dest=org.freedesktop.Accounts
> --type=method_call
> /org/freedesktop/Accounts/User`id -u`
> org.freedesktop.Accounts.User.SetBackgroundFile string:"$USERBACKGROUND"
> 
> Lines above are useless and should go away because freedesktop doest'n have method SetBackgroundFile.
> It seems that SetBackgroundFile is ubuntu specific.
> The useless of those lines can be seen if msd-background-helper is runned in mate in a user terminal.

I will do that on time due it out of the scop of this ticket.
