### ISSUE TITLE
GhostBSD.conf should be move to pkg and repos/usr/local/etc/pkg/repos removed

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/ghostbsd-build#59]
The function code should be update and the FreeBSD.conf remove.

**Comment by angelescuo** [comment]
Where to pkg ?

**Comment by ericbsd** [comment]
Basicaly in ghostbsd-build/pkg/GhostBSD.conf instead of ghostbsd-build/repos/usr/local/etc/pkg/repos/GhostBSD.conf.

**Comment by angelescuo** [comment]
Don't think that needs high priority .
Why should matter gbsd repo conf location  in gbsd-build ?
It can be anywere under gbsd-build but maybe I'm wrong.

**Comment by ericbsd** [comment]
It is simple to do and less directory to move if there is an edit to do.
