### ISSUE TITLE
Add abillity to ghostbsd-build to build anything

### ISSUE THREAD

**Issue by angelescuo** [ghostbsd/ghostbsd-build#62]
Since a netinstaller is in plan to be released we need to add ability to ghostbsd-build to build any environment.
Example : 
For a netinstaller without X it is necesary a iso that boot GhostBSD only.
For a netinstaller with X it is necesary a iso that boot a minimal X and starts netinstaller.
Why not using a single build tool for that instead of maintaining two (ghostbsd-build and assemble-cd) ?
Thank you !

**Comment by ericbsd** [comment]
assemble-cd is planned to be merged at some point. It is not must have now.

**Comment by ericbsd** [comment]
assemble-cd is planned to be merged in ghostbsd-build at some point. assemble-cd was added from Vic's own repository of is work of his concept. There is a lot of things that need to be done before we can get this ready like the persistent config file. Not to merge untile everything sorted out.

**Comment by ericbsd** [comment]
out of the scoop of the project for now.
