### ISSUE TITLE
xdg-user-dirs-update push in iso bad locale

### ISSUE THREAD

**Issue by angelescuo** [ghostbsd/ghostbsd-build#68]
If locale in build host   is not set to default in iso will be pushed dirs for host locale. 
Not a really issue when iso is build on a host with default locale.
This happen because setuser.sh is not launched in a jail env.
If DE uses xdg (is freedesktop compliant) xdg-user-dirs-update is launched when DE starts, so no need to be in setuser.sh
Needs testing for any DE.

**Comment by angelescuo** [comment]
Mate is xdg compliant

**Comment by ericbsd** [comment]
Actually I am not sure why it is still in there since this https://github.com/ghostbsd/ghostbsd-common-settings/tree/master/local/etc/xdg/autostart should take care of it need to be test if it work on the live cd.

**Comment by ericbsd** [comment]
xdg-user-dirs-update line should be removed from setuser.sh

**Comment by angelescuo** [comment]
No need to run xdg-user-dirs-update in live iso from gbsd-build.
It will be runned from xdg/autostart when DE is launched.

**Comment by ericbsd** [comment]
It is already setup there just need to remove the line in setuser.sh

**Comment by angelescuo** [comment]
agree

**Comment by ericbsd** [comment]
https://github.com/ghostbsd/ghostbsd-common-settings/commit/7c7b000ed13dccf3480602f0821dde39225f7adc
