### ISSUE TITLE
dm.sh and user session

### ISSUE THREAD

**Issue by angelescuo** [ghostbsd/ghostbsd-build#73]
Any display manager knows to pick user session from .dmrc file from user home.
Why not using .dmrc file to force a specific session for a DE instead of using code in dm.sh?
If is built a xfce iso then gbsd-xfce-settings should contain a dmrc file for starting a xfce session.
For Mate Session should be mate...
The .dmrc file should be in DE settings. 
for mate DE .dmrc should have : 
[Desktop]
Session=mate
for xfce : 
[Desktop]
Session=xfce
and so on.

**Comment by ericbsd** [comment]
I don't see the need for .dmrc since it is for userspace and not for the GhostBSD default setting.

**Comment by angelescuo** [comment]
It is for GhostBSD default setting because is pushed for all possible users not only for a user .
If you add a dot.dmrc file under /usr/share/skel dot.dmrc file will be pushed to any user as .dmrc when user is created so it is a ghostbsd default setting for a DE.

**Comment by angelescuo** [comment]
At least you have read this.

**Comment by ericbsd** [comment]
The main thing that I disagree with the dot.dmrc in skel it when a user installed two ghostbsd-de-settings packages one will override the other one. Yes, we can add a file conflict option to the port to make sure that the packages will ask the user if he wants to install and or not and it will deinstall the other packages but it is not supported in software and will probably never be supported. Software Station only deletes and installs packages using -y. Also, having conflicted packages does not allow users to have full MATE, XFCE experience i9n the same time.

In contrast, having lightdm.conf setup to the DE to start has default eliminate the dot.dmrc override and packages conflict, the configuration in lightdm.conf is not overridden by package updates or other packages. Also, if there are multiple DE installed in a system LigthDM will default to the last DE selected by the user. LightDM preserves the last DE used for all users.

That why I won't let that in GhostBSD desktops settings ports packages.

**Comment by angelescuo** [comment]
Hi Eric!

I have done some tests and  without .dmrc and user-session in lightdm.conf  or without user-session in lightdm.conf but with .dmrc is the same.
I have tested for mixed env ( mate and cinnamon).
Two ways to have same result.
Also I was very carefull to not have conflicts between packages using .dmrc so not a problem too.
So it's not a real problem since we have already user-session in greeters settings let's keep user session idea.
