### ISSUE TITLE
Remove default loading of drivers in kldlist

### ISSUE THREAD

**Issue by ericbsd** [ghostbsd/ghostbsd-build#74]
Xconfig should start the driver here the issue https://github.com/ghostbsd/xconfig/issues/3 for xconfig when completed and the package is compiled is sync we can remove GPU driver from rc.conf.

**Comment by angelescuo** [comment]
Agree.
All uneeded gpu drivers from kld_list in rc.conf should be removed. Because of them X -configure fails if user doesn't have such a videocard. kld_list should be updated by xconfig which should load needed driver and config xorg.
