### ISSUE TITLE
GhostBSD distribution settings

### ISSUE THREAD

**Issue by angelescuo** [ghostbsd/ghostbsd-build#75]
To be easy to maintain gbsd settings and for packages upgrade and we need a distribution settings file.  Why ?
We need for mate to write same stuff in many files. Same for other DE. 
theme-name , icon-theme-name , background under mate schemas ... and also under greeter settings. 
Any typo can break things.
Why not fill those settings using sed with values taken from distribution settings file when package is installed from pkg-install ?

**Comment by ericbsd** [comment]
I'm closing this issue question are to be asked on GhostBSD forums or GHostBSD Groups.
