### ISSUE TITLE
Two greeters ?

### ISSUE THREAD

**Issue by angelescuo** [ghostbsd/ghostbsd-build#76]
Now under gbsd-build are used slick-greeter for mate, lightdm-gtk-greeter for xfce and I have added slick -greeter for cinnamon, gnome.
Do we really need to maintain two greeters for those DE ?

The only reason to have two greeters should be based on DE toolkits.
A qt one for DE based on qt and a gtk one for gtk based DE to minimize iso size.

**Comment by ericbsd** [comment]
I'm closing this issue question are to be asked on GhostBSD forums or GHostBSD telegram Groups.
